# Generated by Django 5.2.7 on 2025-11-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_credit_hours_course_semester_course_tas_and_more'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='courses_teaching',
            field=models.ManyToManyField(blank=True, related_name='faculty_members', to='core.course'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='office',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
