# Generated by Django 5.2.7 on 2025-11-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_credit_hours_course_semester_course_tas_and_more'),
        ('ta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taprofile',
            name='faculty',
        ),
        migrations.AddField(
            model_name='taprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='taprofile',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='taprofile',
            name='tasks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='taprofile',
            name='courses_assigned',
            field=models.ManyToManyField(blank=True, to='core.course'),
        ),
    ]
